@startuml argocdcanary
autonumber "<b>[0]"
Developer -> GIT : Make changes to current Deployment/Rollout
GIT -> Argocd : Sync Git configuration
Argocd -> AKS : Create canary ReplicaSet
Argocd -> AKS : Update VirtualService to forward 1% percent of traffic to created canary replica set
Argocd -> AKS : Waits for 10 minutes
Argocd -> AKS : Update VirtualService to forward 5% percent of traffic to created canary replica set
Argocd -> AKS : Waits for 10 minutes
Argocd -> AKS : Update stable ReplicaSet to canary release version
Argocd -> AKS : Update VirtualService to forward 100% percent of traffic to new stable replica set
Argocd -> AKS : Tear down canary ReplicaSet
@enduml