apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  istio.server: |
    global:53 {
        errors
        cache 30
        forward . 10.0.30.252:53
    }
