apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  meshConfig:
    accessLogFile: /dev/stdout
  addonComponents:
    istiocoredns:
      enabled: true
  components:
    egressGateways:
      - name: istio-egressgateway
        enabled: true
  values:
    global:
      # Provides dns resolution for global services
      podDNSSearchNamespaces:
        - global
      multiCluster:
        enabled: true
      controlPlaneSecurityEnabled: true
    gateways:
      istio-egressgateway:
        env:
          # Needed to route traffic via egress gateway if desired.
          ISTIO_META_REQUESTED_NETWORK_VIEW: "external"