export MAIN_CLUSTER_CTX=primary
export REMOTE_CLUSTER_CTX=secondary

export MAIN_CLUSTER_NAME=primary
export REMOTE_CLUSTER_NAME=secondary

export MAIN_CLUSTER_NETWORK=primary_network
export REMOTE_CLUSTER_NETWORK=secondary_network