---
# apiVersion: argoproj.io/v1alpha1
# kind: Rollout
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  # strategy:
  #   canary:
  #     canaryMetadata:
  #       labels:
  #         role: canary
  #     stableMetadata:
  #       labels:
  #         role: stable
  #     analysis:
  #       templates:
  #        - templateName: success-rate
  #       startingStep: 2
  #       args:
  #       - name: service-name
  #         value: demo-canary.canary.svc.cluster.local
      # steps:
      # - setWeight: 20
      # - pause:
      #     duration: "15s"
      # - setWeight: 50
      # - pause:
      #     duration: "1m"
      # canaryService: demo-canary
      # stableService: demo
      # trafficRouting:
      #   istio:
      #      virtualService: 
      #       name: istio-vs
      #       routes:
      #       - primary 
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo
      version: blue
  template:
    metadata:
      labels:
        app: demo
        version: blue
    spec:
      containers:
      - name: demo
        image: argoproj/rollouts-demo:orange
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: stable
        ports:
        - name: web
          containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "140m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http-stable
  selector:
    app: demo
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: demo-canary
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http-canary
  selector:
    app: demo
    role: canary
  type: ClusterIP