apiVersion: v1
kind: Service
metadata:
  name: helloworld-primary
  labels:
    app: helloworld-primary
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: helloworld-primary
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-primary
  labels:
    version: v1
    app: helloworld-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-primary
      version: v1
  template:
    metadata:
      labels:
        app: helloworld-primary
        version: v1
    spec:
      containers:
      - name: helloworld-primary
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000